# Generated by Django 5.1 on 2024-09-10 21:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Titre')),
                ('type_media', models.CharField(choices=[('DVD', 'Dvd'), ('BOOK', 'Book'), ('CD', 'Cd')], max_length=30, verbose_name='Type de média')),
                ('availability', models.BooleanField(default='True')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='librarian.media')),
                ('author', models.CharField(max_length=50)),
            ],
            bases=('librarian.media',),
        ),
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='librarian.media')),
                ('entertainer', models.CharField(max_length=50)),
            ],
            bases=('librarian.media',),
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='librarian.media')),
                ('producer', models.CharField(max_length=50)),
            ],
            bases=('librarian.media',),
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='librarian.media')),
                ('borrowingDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrower', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='borrower.borrower')),
            ],
            bases=('librarian.media',),
        ),
    ]
