# Generated by Django 5.1 on 2024-09-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type_media',
            field=models.CharField(choices=[('DVD', 'Dvd'), ('BOOK', 'Livre'), ('CD', 'Cd')], max_length=30, verbose_name='Type de média'),
        ),
    ]
