# Generated by Django 5.1 on 2024-09-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_borrowing_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='type_media',
        ),
    ]
